"""
Typed data models for HeatGuard AI.

Pydantic gives us automatic validation for free, which doubles as our
"validate API responses before use" requirement: any malformed
FortyGuard (or mock) response will fail model construction instead of
silently propagating bad data into the UI or the AI layer.

NOTE: RiskScore, AIAnalysis, and Hotspot are defined here now (Phase 2)
as the shared schema contract, but they are only *populated* by real
logic in Phase 3 (risk_scoring.py, hotspot_detection.py, the AI agent).
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator

DataSource = Literal["live", "mock"]
Confidence = Literal["high", "partial", "low"]
RiskLevel = Literal["Low", "Moderate", "High", "Extreme"]
Priority = Literal["Low", "Medium", "High", "Critical"]


class TemperatureReading(BaseModel):
    """A single hyperlocal temperature reading for one location."""

    location_id: str
    name: str
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    temperature_c: float
    timestamp: datetime
    source: DataSource
    confidence: Confidence

    @field_validator("temperature_c")
    @classmethod
    def sane_temperature_range(cls, value: float) -> float:
        # Generous but real-world bounds: catches obviously corrupt
        # payloads (e.g. unit errors, parsing bugs) without pretending
        # to be a climate model.
        if not -90 <= value <= 60:
            raise ValueError(
                f"temperature_c={value} is outside plausible bounds (-90..60 C)"
            )
        return value


class RiskScore(BaseModel):
    """
    Deterministic, code-calculated risk score for a location.

    Populated in Phase 3 by app/utils/risk_scoring.py. Never set by an LLM.
    """

    location_id: str
    score: int = Field(ge=0, le=100)
    level: RiskLevel
    inputs: dict[str, float | str] = Field(default_factory=dict)
    confidence: Confidence


class AIAnalysis(BaseModel):
    """
    Structured AI Heat Analysis output for a location.

    `temperature` and `risk_score` are always copied in from code-computed
    values (never generated by the LLM). `reasoning`, `affected_groups`,
    and `recommended_actions` are LLM-authored but constrained to the
    provided data / curated taxonomies. Populated in Phase 3.
    """

    location_id: str
    temperature: float
    risk_score: int = Field(ge=0, le=100)
    risk_level: RiskLevel
    reasoning: str
    affected_groups: list[str] = Field(default_factory=list)
    recommended_actions: list[str] = Field(default_factory=list)
    priority: Priority
    data_confidence: Confidence


class Hotspot(BaseModel):
    """
    A location flagged as a heat outlier relative to its local baseline.

    Populated in Phase 3 by app/utils/hotspot_detection.py (code-based,
    not AI-based).
    """

    location_id: str
    name: str
    temperature_c: float
    delta_vs_baseline_c: float
    risk_level: RiskLevel
    suggested_intervention_type: str
